---
apiVersion: v1
automountServiceAccountToken: true
kind: ServiceAccount
metadata:
  name: dns-mutation-webhook
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dns-mutation-webhook
rules:
- apiGroups: [""]
  resources:
    - configmaps
  verbs:
    - get
    - list
    - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dns-mutation-webhook
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: dns-mutation-webhook
subjects:
- kind: ServiceAccount
  name: dns-mutation-webhook
  namespace: default
---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    kubernetes.io/service-account.name: dns-mutation-webhook
  name: secret-sa-dns-mutation-webhook
  namespace: default
type: kubernetes.io/service-account-token