apiVersion: apps/v1
kind: Deployment
metadata:
  name: dns-mutation-webhook
  labels:
    app: dns-mutation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dns-mutation
  template:
    metadata:
      labels:
        app: dns-mutation
    spec:
      containers:
      - name: webhook
        image: ugurozturk99/dnsmutationwebhook:${CI_PIPELINE_ID}
        ports:
        - containerPort: 443
        resources:
          requests:
            cpu: "1m"
        env:
        - name: LOG_LEVEL
          value: "info"
        - name: NDOTS
          value: "2"
        - name: TIMEOUT
          value: "2"
        - name: ATTEMTPS
          value: "1"
        - name: NODELOCALDNS_IP
          values: "169.254.25.10"
        volumeMounts:
        - mountPath: "/app/properties.yaml"
          name: config
          subPath: "properties.yaml"
        - name: certs-volume
          readOnly: true
          mountPath: "/certs"
        imagePullPolicy: Always
      volumes:
      - name: config
        configMap:
          name: dns-mutation-cm
          items:
          - key: "properties.yaml"
            path: "properties.yaml"
      - name: certs-volume
        secret:
          secretName: dns-admission-tls
